# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmswitch" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/devopshouse/tmswitch/releases/download/v#{version}/tmswitch_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/devopshouse/tmswitch/"
      sha256 "b3926a1888385aee8f6345a629ed7901e4d00d27195ea78ba349ada150b75089"
    end
    on_arm do
      url "https://github.com/devopshouse/tmswitch/releases/download/v#{version}/tmswitch_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/devopshouse/tmswitch/"
      sha256 "8cc8950ccac857b48c1e03ecbfc2f2f7500918cc5927fd0d826d3c5c8514006a"
    end
  end

  name "tmswitch"
  desc "Switch between different versions of Terramate"
  homepage "https://github.com/devopshouse/tmswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmswitch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmswitch"]
    end
  end

  # No zap stanza required

end
