# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmswitch" do
  name "tmswitch"
  desc "Switch between different versions of Terramate"
  homepage "https://github.com/devopshouse/tmswitch"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmswitch"

  on_macos do
    on_intel do
      url "https://github.com/devopshouse/tmswitch/releases/download/v#{version}/tmswitch_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/devopshouse/tmswitch/"
      sha256 "c32dd786b451df27b979bbfdfb7149fe69b5e5dbf7fb7d4c7d56a0b8dc9b3772"
    end
    on_arm do
      url "https://github.com/devopshouse/tmswitch/releases/download/v#{version}/tmswitch_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/devopshouse/tmswitch/"
      sha256 "33e6e9a7d9d0f07c86d9ad149f3ca787c6687b2ac3f7d922923540be42f89dd5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmswitch"]
    end
  end

  # No zap stanza required
end
