# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmswitch < Formula
  desc "Switch between different versions of Terramate"
  homepage "https://github.com/devopshouse/tmswitch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devopshouse/tmswitch/releases/download/v0.1.0/tmswitch_0.1.0_darwin_x86_64.tar.gz"
      sha256 "038990237ea8f15eb4be32a0a26faf9149f8df1ede5d8679ceb6ececa438ef8d"

      define_method(:install) do
        bin.install "tmswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devopshouse/tmswitch/releases/download/v0.1.0/tmswitch_0.1.0_darwin_arm64.tar.gz"
      sha256 "f824b6a5d1ef8107d31e15ce0e71bd33ef2af74f578f16df04a2625ec5537baf"

      define_method(:install) do
        bin.install "tmswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devopshouse/tmswitch/releases/download/v0.1.0/tmswitch_0.1.0_linux_x86_64.tar.gz"
      sha256 "a276d372a797eb940a2bc0dcc291ae6b6f9c0bc3343c5c6bd101d772f4c9a138"
      define_method(:install) do
        bin.install "tmswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devopshouse/tmswitch/releases/download/v0.1.0/tmswitch_0.1.0_linux_arm64.tar.gz"
      sha256 "f082bb9c10f96b4fda7ad239ef001efa276975aca354ce785770b7432c994608"
      define_method(:install) do
        bin.install "tmswitch"
      end
    end
  end

  test do
    assert_match "tmswitch version:", shell_output("#{bin}/tmswitch --version")
  end
end
